### Summary Statistics

Summary statistics provide a concise overview of a dataset's distribution. Here's a breakdown of the commonly calculated metrics:

**Central Tendency**
- **Mean**: The average value of the dataset. It's calculated by summing all values and dividing by the number of values.
- **Median**: The middle value in a dataset when the values are arranged in ascending order. It's a robust measure that's less sensitive to outliers than the mean.
- **Mode**: The most frequent value in the dataset. There can be one mode (unimodal), multiple modes (multimodal), or no mode.

**Dispersion**
- **Standard Deviation**: Measures the spread of the data around the mean. A higher standard deviation indicates greater variability.
- **Variance**: The square of the standard deviation.
- **Range**: The difference between the maximum and minimum values.
- **Interquartile Range (IQR)**: The difference between the 75th percentile (Q3) and the 25th percentile (Q1). It measures the spread of the middle 50% of the data.
---

**Category Name: Flow rate and Inter-arrival time**

These are the features we will process in this notebook:
- Flow Bytes/s: The average number of bytes transferred per second during the flow.
- Flow Packets/s: The average number of packets transferred per second during the flow.
- Flow IAT Mean, Std, Max, Min: The mean, standard deviation, maximum, and minimum interarrival times for the entire flow.
- Fwd IAT Total, Mean, Std, Max, Min: The total, mean, standard deviation, maximum, and minimum interarrival times for forward packets.
- Bwd IAT Total, Mean, Std, Max, Min: The total, mean, standard deviation, maximum, and minimum interarrival times for backward packets.

In [2]:
# Importing important libraries 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os 
import json

In [3]:
# Functions 
# Update this code block to add more functions as per need
def read_data(data_path: str, usecols: list) -> pd.DataFrame:
    """
    This function reads the data from the data path
    """
    data = pd.read_csv(data_path, usecols=usecols)
    return data

**Data**

In [4]:
# Read data from filepath 
# This file path is for temporary usage (For EDA)
# It will be removed once the task is completed 

file_path = "dataset.csv"
# Columns in this category
columns_to_read = ['Flow Bytes/s',
       'Flow Packets/s', 'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max',
       'Flow IAT Min', 'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std',
       'Fwd IAT Max', 'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean',
       'Bwd IAT Std', 'Bwd IAT Max', 'Bwd IAT Min']

# Read the data
try:
    data = read_data(file_path, usecols = columns_to_read)
    print(f"Successfully read {len(data.columns)} features")
except:
    print("File not found!")
    print("[INFO] Please place the dataset.csv in the directory for use!")

Successfully read 16 features

**Analysis**

In [6]:
# Pandas Describe func
data.describe()

,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Flow IAT Std,Flow IAT Max,Flow IAT Min,Fwd IAT Total,Fwd IAT Mean,Fwd IAT Std,Fwd IAT Max,Fwd IAT Min,Bwd IAT Total,Bwd IAT Mean,Bwd IAT Std,Bwd IAT Max,Bwd IAT Min
count,3.190424e+06,3.231475e+06,3.189766e+06,3.189766e+06,3.189766e+06,3.189766e+06,3.231475e+06,3.231475e+06,3.231475e+06,3.231475e+06,3.231475e+06,3.231475e+06,3.231475e+06,3.231475e+06,3.231475e+06,3.231475e+06
mean,inf,inf,2.735251e+05,3.360596e+05,1.276584e+06,8.328863e+04,6.945646e+06,3.285592e+05,3.410078e+05,1.256459e+06,1.179019e+05,6.068053e+06,1.277624e+05,1.533856e+05,7.162992e+05,3.828208e+04
std,NaN,NaN,1.508600e+06,2.094611e+06,6.032778e+06,9.103900e+05,2.452922e+07,1.975864e+06,2.020715e+06,5.977838e+06,1.475624e+06,2.387446e+07,1.472715e+06,1.031695e+06,3.916720e+06,1.147860e+06
min,0.000000e+00,1.676950e-02,4.000000e+00,0.000000e+00,4.000000e+00,-3.700000e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.000000e+00
25%,1.311855e+04,9.950051e+01,7.968889e+02,1.691476e+03,6.120000e+03,4.000000e+00,7.436000e+03,1.286400e+03,1.905740e+03,5.221000e+03,1.400000e+01,2.382000e+03,4.445000e+02,4.625197e+02,1.258000e+03,1.200000e+01
50%,2.953897e+04,3.049976e+02,3.698667e+03,9.634148e+03,3.084300e+04,8.000000e+00,3.748100e+04,7.329000e+03,1.270876e+04,2.996400e+04,2.300000e+01,2.706800e+04,6.331750e+03,1.030339e+04,2.231200e+04,2.200000e+01
75%,1.341632e+05,1.664145e+03,1.121073e+04,2.693886e+04,1.073290e+05,1.100000e+01,1.288720e+05,2.204600e+04,3.565635e+04,1.043795e+05,3.200000e+01,8.073100e+04,1.769325e+04,2.945571e+04,6.433400e+04,3.400000e+01
max,inf,inf,1.192641e+08,8.399294e+07,1.199621e+08,1.192641e+08,1.200000e+08,1.199622e+08,8.365714e+07,1.199622e+08,1.199622e+08,1.200000e+08,1.199621e+08,8.366532e+07,1.199621e+08,1.199621e+08

In [8]:
# Unique 
data.nunique()

Flow Bytes/s      2260437
Flow Packets/s    1222559
Flow IAT Mean     1510578
Flow IAT Std      3053101
Flow IAT Max       498232
Flow IAT Min        40359
Fwd IAT Total      614738
Fwd IAT Mean      1191586
Fwd IAT Std       2976829
Fwd IAT Max        498469
Fwd IAT Min         58963
Bwd IAT Total      455963
Bwd IAT Mean      1005295
Bwd IAT Std       2706225
Bwd IAT Max        450557
Bwd IAT Min         30776
dtype: int64

> Fwd and Bwd IAT min columns has less unique values showing the minimum inter arrival time for both Fwd and Bwd remain same throughout the flow.

In [14]:
data[['Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Fwd IAT Total', 'Bwd IAT Total']].describe()

,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Fwd IAT Total,Bwd IAT Total
count,3.190424e+06,3.231475e+06,3.189766e+06,3.231475e+06,3.231475e+06
mean,inf,inf,2.735251e+05,6.945646e+06,6.068053e+06
std,NaN,NaN,1.508600e+06,2.452922e+07,2.387446e+07
min,0.000000e+00,1.676950e-02,4.000000e+00,0.000000e+00,0.000000e+00
25%,1.311855e+04,9.950051e+01,7.968889e+02,7.436000e+03,2.382000e+03
50%,2.953897e+04,3.049976e+02,3.698667e+03,3.748100e+04,2.706800e+04
75%,1.341632e+05,1.664145e+03,1.121073e+04,1.288720e+05,8.073100e+04
max,inf,inf,1.192641e+08,1.200000e+08,1.200000e+08

> There are data instances which has values 'infinity', we will replace this with NaN

In [34]:
dt = data.replace([np.inf, -np.inf], np.NaN)  # Replace 'inf' with NaN
dt = dt.dropna()  # Drop NaN values

# or
# Put the max value of that column in place of 'inf'
# df = data.replace([np.inf, -np.inf], data.max())

In [35]:
dt[['Flow Bytes/s', 'Flow Packets/s', 'Flow IAT Mean', 'Fwd IAT Total', 'Bwd IAT Total']].describe()

,Flow Bytes/s,Flow Packets/s,Flow IAT Mean,Fwd IAT Total,Bwd IAT Total
count,3.189766e+06,3.189766e+06,3.189766e+06,3.189766e+06,3.189766e+06
mean,1.555212e+06,4.273891e+03,2.735251e+05,7.036466e+06,6.147398e+06
std,1.942899e+07,1.105574e+04,1.508600e+06,2.467612e+07,2.401989e+07
min,0.000000e+00,1.676950e-02,4.000000e+00,0.000000e+00,0.000000e+00
25%,1.311718e+04,9.711210e+01,7.968889e+02,8.271000e+03,2.923000e+03
50%,2.952746e+04,2.969201e+02,3.698667e+03,3.853300e+04,2.794300e+04
75%,1.339286e+05,1.485800e+03,1.121073e+04,1.335310e+05,8.196400e+04
max,1.489628e+09,5.000000e+05,1.192641e+08,1.200000e+08,1.200000e+08

> Flow Bytes/s has a wide spread of data ranging from 0 to crores. Although, most instances fall below 1.33 lakhs (approx.).

> Flow Packets/s has mean closer to the max value, indicating that average number of packets transferred in a flow is generally higher.

> Flow IAT Mean shows a wide spread of data ranging from 0 to crores. Indicating, the inter arrival time mean can vary in a wide range.